
#include <LiquidCrystal_I2C.h>
#include <Wire.h>


// DEFINICION DE PINES

#define ENVIAR 7      // BOTON PARA ENVIAR LA INFO AL PC
#define HERRADURA 6   // SENSOR DE HERRADURA QUE MEDIRÁ EL LARGO DEL ROLLO
#define TESTIGO 5     // BOTON PARA CALIBRAR CON UN PESO DE CONTROL
#define ZERO 4        // BOTON PARA PONER EN CERO EL MEDIDOR

// DEFINICION DE PARAMETROS MEDIDOR LONGITUD
#define RADIOS 4  // CANTIDAD DE DIVIIONES QUE TIENE LA RUEDA PARA MEDIR LONGITUD
#define R 4       // RADIO DE LA RUEDA QUE SE UTILIZA PARA MEDIR LA LONGITUD

//



void setup() {
  pinMode(ENVIAR,INPUT);
  pinMode(HERRADURA, INPUT);
  pinMode(TESTIGO, INPUT);
  pinMode(ZERO, INPUT);
}

void loop() {
  
}
